# Generated by Django 5.2.7 on 2025-10-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
